-- MySQL Script generated by MySQL Workbench
-- Sun Sep 28 21:23:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_listaCompras
-- -----------------------------------------------------
-- Banco para a Criação da estrutura do programa 

-- -----------------------------------------------------
-- Schema db_listaCompras
--
-- Banco para a Criação da estrutura do programa 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_listaCompras` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_listaCompras` ;

-- -----------------------------------------------------
-- Table `db_listaCompras`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`grupos` (
  `idClasses` INT NOT NULL AUTO_INCREMENT,
  `nome_classe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClasses`),
  UNIQUE INDEX `nome_classe_UNIQUE` (`nome_classe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `Classes_idClasses` INT NOT NULL,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `imagem_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`, `Classes_idClasses`),
  UNIQUE INDEX `nome_categoria_UNIQUE` (`nome_categoria` ASC) VISIBLE,
  INDEX `fk_categorias_Classes1_idx` (`Classes_idClasses` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_Classes1`
    FOREIGN KEY (`Classes_idClasses`)
    REFERENCES `db_listaCompras`.`grupos` (`idClasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`subcategoria` (
  `idsubcategoria` INT NOT NULL,
  `categorias_id_categoria` INT NOT NULL,
  `nome_subcategoria` VARCHAR(45) NOT NULL,
  `db_subcategoria` VARCHAR(45) NOT NULL,
  `Imagem_subcategoria` VARCHAR(45) NULL,
  `descricao_subcategoria` VARCHAR(100) NOT NULL,
  `unidade_medida` VARCHAR(20) NULL,
  PRIMARY KEY (`idsubcategoria`, `categorias_id_categoria`),
  INDEX `fk_subcategoria_categorias1_idx` (`categorias_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categorias1`
    FOREIGN KEY (`categorias_id_categoria`)
    REFERENCES `db_listaCompras`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cargo_funcionario` VARCHAR(45) NOT NULL,
  `nivel_funcionario` INT NOT NULL,
  `usuario_funcionario` VARCHAR(45) NOT NULL,
  `senha_funcionario` VARCHAR(128) NOT NULL,
  `email_funcionario` VARCHAR(100) NOT NULL,
  `foi_criado_em` DATE NOT NULL,
  `ultimo_acesso_em` DATETIME NOT NULL,
  PRIMARY KEY (`idfuncionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`dados_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`dados_pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `funcionario_pedido` INT NOT NULL,
  `datetime_pedido` VARCHAR(45) NOT NULL,
  `nome_projeto` VARCHAR(45) NOT NULL,
  `nome_lista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `funcionario_escolhido_idx` (`funcionario_pedido` ASC) VISIBLE,
  CONSTRAINT `funcionario_escolhido`
    FOREIGN KEY (`funcionario_pedido`)
    REFERENCES `db_listaCompras`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`pedido` (
  `linha_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_dados_pedido` INT NOT NULL,
  `aceito` TINYINT NULL,
  `quantidade` INT NOT NULL,
  `medida` VARCHAR(20) NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  `produto` VARCHAR(200) NOT NULL,
  `fabricante` VARCHAR(45) NULL,
  `cod_fabricante` VARCHAR(45) NULL,
  PRIMARY KEY (`linha_pedido`),
  INDEX `id_dados_pedido_idx` (`id_dados_pedido` ASC) VISIBLE,
  CONSTRAINT `id_dados_pedido`
    FOREIGN KEY (`id_dados_pedido`)
    REFERENCES `db_listaCompras`.`dados_pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`chefia_direta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`chefia_direta` (
  `id_confere` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT NOT NULL,
  `id_chefia` INT NOT NULL,
  INDEX `fk_chefia_direta_funcionarios1_idx` (`id_funcionario` ASC) VISIBLE,
  PRIMARY KEY (`id_confere`),
  INDEX `fk_chefia_direta_idx` (`id_chefia` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `db_listaCompras`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chefia_direta`
    FOREIGN KEY (`id_chefia`)
    REFERENCES `db_listaCompras`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`pedido_aprova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`pedido_aprova` (
  `idpedido_aprova` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `id_chefia_aprova` INT NOT NULL,
  `pedido_aprovado` TINYINT NULL,
  PRIMARY KEY (`idpedido_aprova`),
  INDEX `fk_pedido_aprova_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_chefia_idx` (`id_chefia_aprova` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_aprova_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `db_listaCompras`.`pedido` (`linha_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chefia`
    FOREIGN KEY (`id_chefia_aprova`)
    REFERENCES `db_listaCompras`.`chefia_direta` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`Renomear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`Renomear` (
  `idRenomear` INT NOT NULL,
  `renomear_coluna` VARCHAR(45) NOT NULL,
  `renomear_colunaRenomeada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRenomear`),
  UNIQUE INDEX `renomear_coluna_UNIQUE` (`renomear_coluna` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
