-- MySQL Script generated by MySQL Workbench
-- Fri Aug 29 23:35:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_listaCompras
-- -----------------------------------------------------
-- Banco para a Criação da estrutura do programa 

-- -----------------------------------------------------
-- Schema db_listaCompras
--
-- Banco para a Criação da estrutura do programa 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_listaCompras` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `db_listaCompras` ;

-- -----------------------------------------------------
-- Table `db_listaCompras`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NULL,
  `imagem_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`subcategoria` (
  `idsubcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome_subcategoria` VARCHAR(45) NOT NULL,
  `db_subcategoria` VARCHAR(45) NOT NULL,
  `Imagem_subcategoria` VARCHAR(45) NULL,
  `fk_subcategoria_categoria` INT NOT NULL,
  `descricao_subcategoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idsubcategoria`, `fk_subcategoria_categoria`),
  INDEX `fk_subcategoria_idx` (`fk_subcategoria_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria`
    FOREIGN KEY (`fk_subcategoria_categoria`)
    REFERENCES `db_listaCompras`.`categorias` (`idcategorias`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `codigo` VARCHAR(20) NOT NULL,
  `produto` VARCHAR(200) NOT NULL,
  `aceito` TINYINT NULL,
  PRIMARY KEY (`idpedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cargo_funcionario` VARCHAR(45) NOT NULL,
  `nivel_funcionario` INT NOT NULL,
  `usuario_funcionario` VARCHAR(45) NOT NULL,
  `senha_funcionario` VARCHAR(128) NULL,
  `email_funcionario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfuncionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`chefia_direta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`chefia_direta` (
  `id_confere` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_confere`, `id_funcionario`),
  INDEX `fk_chefia_direta_funcionarios1_idx` (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_chefia_direta_funcionarios1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `db_listaCompras`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_listaCompras`.`pedido_aprova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_listaCompras`.`pedido_aprova` (
  `idpedido_aprova` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `id_chefia_aprova` INT NOT NULL,
  `pedido_aprovado` TINYINT NULL,
  PRIMARY KEY (`idpedido_aprova`),
  INDEX `fk_pedido_aprova_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_chefia_idx` (`id_chefia_aprova` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_aprova_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `db_listaCompras`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chefia`
    FOREIGN KEY (`id_chefia_aprova`)
    REFERENCES `db_listaCompras`.`chefia_direta` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
